export const FROM_INTERIOR = 'FROM_INTERIOR';
export const FROM_EXTERIOR = 'FROM_EXTERIOR';
export const END_NAVIGATION = 'END_NAVIGATION';
export const SEND_END_DESTINATION = 'SEND_END_DESTINATION';
